name: assets
description: Zither Harp Nomna (Assets).
publish_to: 'none'
version: 1.0.0
repository: https://github.com/zitherharpnomna/assets

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - icons/
    - images/
    - favicons/
  fonts:
    - family: nomnatong
      fonts:
        - asset: fonts/nom-na-tong.otf