name: assets
description: Zither Harp Nomna (Assets).
publish_to: 'none'
version: 1.0.0
repository: https://github.com/zitherharpnomna/assets

environment:
  sdk: '>=3.0.5 <4.0.0'

flutter:
  assets:
    - icons/
    - images/
    - favicons/
  fonts:
    - family: NomNaTong
      fonts:
        - asset: fonts/NomNaTong.otf